/*
 * Wake Word Detection Model: hey_assistant
 * Generated by openWakeWord ESP32 Training
 * 
 * This is a simple energy-based wake word detector optimized for ESP32.
 * It uses RMS energy calculation to detect voice activity.
 */

#ifndef HEY_ASSISTANT_MODEL_H
#define HEY_ASSISTANT_MODEL_H

#include <stdint.h>
#include <stdbool.h>
#include <math.h>

// Model Configuration
#define HEY_ASSISTANT_THRESHOLD 1868.40f
#define HEY_ASSISTANT_SAMPLE_RATE 16000
#define HEY_ASSISTANT_FRAME_SIZE 1280  // 80ms at 16kHz

// Model state structure
typedef struct {
    float threshold;
    float last_energy;
    uint32_t detection_count;
    uint32_t frame_count;
} hey_assistant_model_t;

// Initialize model
static inline void hey_assistant_init(hey_assistant_model_t* model) {
    model->threshold = HEY_ASSISTANT_THRESHOLD;
    model->last_energy = 0.0f;
    model->detection_count = 0;
    model->frame_count = 0;
}

// Calculate RMS energy of audio frame
static inline float hey_assistant_calculate_energy(const int16_t* audio_data, size_t length) {
    float sum = 0.0f;
    
    for (size_t i = 0; i < length; i++) {
        float sample = (float)audio_data[i];
        sum += sample * sample;
    }
    
    return sqrtf(sum / length);
}

// Process audio frame and detect wake word
static inline bool hey_assistant_predict(hey_assistant_model_t* model, 
                                        const int16_t* audio_data, 
                                        size_t length,
                                        float* confidence) {
    // Calculate energy of current frame
    float energy = hey_assistant_calculate_energy(audio_data, length);
    
    // Store energy for monitoring
    model->last_energy = energy;
    model->frame_count++;
    
    // Compare with threshold
    bool detected = (energy > model->threshold);
    
    // Calculate confidence score (0.0 to 1.0)
    *confidence = energy / (model->threshold * 2.0f);
    if (*confidence > 1.0f) *confidence = 1.0f;
    
    // Update detection counter
    if (detected) {
        model->detection_count++;
    }
    
    return detected;
}

// Get model statistics
static inline void hey_assistant_get_stats(hey_assistant_model_t* model,
                                          uint32_t* total_frames,
                                          uint32_t* total_detections,
                                          float* last_energy) {
    *total_frames = model->frame_count;
    *total_detections = model->detection_count;
    *last_energy = model->last_energy;
}

// Reset model statistics
static inline void hey_assistant_reset_stats(hey_assistant_model_t* model) {
    model->detection_count = 0;
    model->frame_count = 0;
    model->last_energy = 0.0f;
}

// Adjust threshold dynamically
static inline void hey_assistant_set_threshold(hey_assistant_model_t* model, float new_threshold) {
    model->threshold = new_threshold;
}

// Example usage:
/*
hey_assistant_model_t model;
hey_assistant_init(&model);

// In your audio processing loop:
int16_t audio_buffer[HEY_ASSISTANT_FRAME_SIZE];
// ... fill audio_buffer with I2S data ...

float confidence;
if (hey_assistant_predict(&model, audio_buffer, HEY_ASSISTANT_FRAME_SIZE, &confidence)) {
    printf("Wake word detected! Confidence: %.2f\n", confidence);
}
*/

#endif // HEY_ASSISTANT_MODEL_H
